# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency:  2
:queues:
  - [default, 1]
  - [mailers, 1]

production:
  :pidfile: /var/www/kangyu/shared/tmp/pids/sidekiq.pid
